{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOO49ruGdF+UYA0mCM9F66u",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "0603b853fec2405a86222c670e09c35b": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DropdownModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DropdownModel",
            "_options_labels": [
              "All",
              "Manager",
              "Pioneer/Executive",
              "Player",
              "Umpire"
            ],
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "DropdownView",
            "description": "Hall of Famer Type:",
            "description_tooltip": null,
            "disabled": false,
            "index": 3,
            "layout": "IPY_MODEL_c89ef2222f23468aa01d3c1c2f0804b9",
            "style": "IPY_MODEL_e079135cbc564482bafba4967ac6ce48"
          }
        },
        "c89ef2222f23468aa01d3c1c2f0804b9": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "e079135cbc564482bafba4967ac6ce48": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "e239de91dcea453f8f46e7c4c0133a3f": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DropdownModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DropdownModel",
            "_options_labels": [
              "Batting Stats",
              "Pitching Stats",
              "Other Stats"
            ],
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "DropdownView",
            "description": "Stats Type:",
            "description_tooltip": null,
            "disabled": false,
            "index": 2,
            "layout": "IPY_MODEL_d32211b0612842f394b1bb1544b9811d",
            "style": "IPY_MODEL_eaf4b9ced5134ecb95f8e1e12180282d"
          }
        },
        "d32211b0612842f394b1bb1544b9811d": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "eaf4b9ced5134ecb95f8e1e12180282d": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "6b2781401d6046a38ed7031f5ab0434a": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DropdownModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DropdownModel",
            "_options_labels": [
              "Addie Joss",
              "Adrian Beltre",
              "Al Kaline",
              "Al Simmons",
              "Alan Trammell",
              "Amos Rusie",
              "Andre Dawson",
              "Andruw Jones",
              "Andy Cooper",
              "Arky Vaughan",
              "Babe Ruth",
              "Barry Larkin",
              "Ben Taylor",
              "Bert Blyleven",
              "Bid McPhee",
              "Bill Dickey",
              "Bill Foster",
              "Bill Mazeroski",
              "Bill Terry",
              "Billy Hamilton",
              "Billy Herman",
              "Billy Wagner",
              "Billy Williams",
              "Biz Mackey",
              "Bob Feller",
              "Bob Gibson",
              "Bob Lemon",
              "Bobby Doerr",
              "Bobby Wallace",
              "Brooks Robinson",
              "Bruce Sutter",
              "Buck Ewing",
              "Buck Leonard",
              "Bullet Rogan",
              "Burleigh Grimes",
              "CC Sabathia",
              "Cal Ripken Jr.",
              "Cap Anson",
              "Carl Hubbell",
              "Carl Yastrzemski",
              "Carlos Beltran",
              "Carlton Fisk",
              "Catfish Hunter",
              "Charles Bender",
              "Charlie Gehringer",
              "Chick Hafey",
              "Chipper Jones",
              "Christy Mathewson",
              "Chuck Klein",
              "Cool Papa Bell",
              "Craig Biggio",
              "Crista³bal Torriente",
              "Cy Young",
              "Dan Brouthers",
              "Dave Bancroft",
              "Dave Parker",
              "Dave Winfield",
              "David Ortiz",
              "Dazzy Vance",
              "Deacon White",
              "Dennis Eckersley",
              "Derek Jeter",
              "Dick Allen",
              "Dizzy Dean",
              "Don Drysdale",
              "Don Sutton",
              "Duke Snider",
              "Earl Averill",
              "Earle Combs",
              "Early Wynn",
              "Ed Delahanty",
              "Ed Walsh",
              "Edd Roush",
              "Eddie Collins",
              "Eddie Mathews",
              "Eddie Murray",
              "Eddie Plank",
              "Edgar Marta­nez",
              "Elmer Flick",
              "Enos Slaughter",
              "Eppa Rixey",
              "Ernie Banks",
              "Ernie Lombardi",
              "Fergie Jenkins",
              "Frank Chance",
              "Frank Robinson",
              "Frank Thomas",
              "Frankie Frisch",
              "Fred Clarke",
              "Fred McGriff",
              "Freddie Lindstrom",
              "Gabby Hartnett",
              "Gary Carter",
              "Gaylord Perry",
              "George Brett",
              "George Davis",
              "George Kell",
              "George Kelly",
              "George Sisler",
              "Gil Hodges",
              "Goose Goslin",
              "Greg Maddux",
              "Grover Alexander",
              "Hack Wilson",
              "Hal Newhouser",
              "Hank Greenberg",
              "Harmon Killebrew",
              "Harold Baines",
              "Harry Heilmann",
              "Harry Hooper",
              "Heinie Manush",
              "Henry Aaron",
              "Herb Pennock",
              "Hilton Smith",
              "Home Run Baker",
              "Honus Wagner",
              "Hoyt Wilhelm",
              "Hugh Duffy",
              "Hughie Jennings",
              "Ichiro Suzuki",
              "Ivan Rodriguez",
              "Jack Chesbro",
              "Jack Morris",
              "Jackie Robinson",
              "Jake Beckley",
              "Jeff Bagwell",
              "Jeff Kent",
              "Jesse Burkett",
              "Jesse Haines",
              "Jim Bottomley",
              "Jim Bunning",
              "Jim Kaat",
              "Jim O'Rourke",
              "Jim Palmer",
              "Jim Rice",
              "Jim Thome",
              "Jimmie Foxx",
              "Jimmy Collins",
              "Joe Cronin",
              "Joe DiMaggio",
              "Joe Gordon",
              "Joe Kelley",
              "Joe Mauer",
              "Joe McGinnity",
              "Joe Medwick",
              "Joe Morgan",
              "Joe Sewell",
              "Joe Tinker",
              "Joe Williams",
              "John Clarkson",
              "John Henry Lloyd",
              "John Smoltz",
              "John Ward",
              "Johnny Bench",
              "Johnny Evers",
              "Johnny Mize",
              "Jose Mendez",
              "Josh Gibson",
              "Juan Marichal",
              "Jud Wilson",
              "Judy Johnson",
              "Ken Griffey Jr.",
              "Kid Nichols",
              "Kiki Cuyler",
              "King Kelly",
              "Kirby Puckett",
              "Larry Doby",
              "Larry Walker",
              "Lee Smith",
              "Lefty Gomez",
              "Lefty Grove",
              "Leon Day",
              "Lloyd Waner",
              "Lou Boudreau",
              "Lou Brock",
              "Lou Gehrig",
              "Louis Santop",
              "Luis Aparicio",
              "Luke Appling",
              "Mariano Rivera",
              "Marta­n Dihigo",
              "Max Carey",
              "Mel Ott",
              "Mickey Cochrane",
              "Mickey Mantle",
              "Mickey Welch",
              "Mike Mussina",
              "Mike Piazza",
              "Mike Schmidt",
              "Minnie Minoso",
              "Monte Irvin",
              "Mordecai Brown",
              "Mule Suttles",
              "Nap Lajoie",
              "Nellie Fox",
              "Nolan Ryan",
              "Old Hoss Radbourn",
              "Orlando Cepeda",
              "Oscar Charleston",
              "Ozzie Smith",
              "Paul Molitor",
              "Paul Waner",
              "Pedro Martinez",
              "Pee Wee Reese",
              "Pete Hill",
              "Phil Niekro",
              "Phil Rizzuto",
              "Pie Traynor",
              "Pud Galvin",
              "Rabbit Maranville",
              "Ralph Kiner",
              "Randy Johnson",
              "Ray Brown",
              "Ray Dandridge",
              "Ray Schalk",
              "Red Faber",
              "Red Ruffing",
              "Red Schoendienst",
              "Reggie Jackson",
              "Rich Gossage",
              "Richie Ashburn",
              "Rick Ferrell",
              "Rickey Henderson",
              "Roberto Alomar",
              "Roberto Clemente",
              "Robin Roberts",
              "Robin Yount",
              "Rod Carew",
              "Roger Bresnahan",
              "Roger Connor",
              "Rogers Hornsby",
              "Rollie Fingers",
              "Ron Santo",
              "Ross Youngs",
              "Roy Campanella",
              "Roy Halladay",
              "Rube Marquard",
              "Rube Waddell",
              "Ryne Sandberg",
              "Sam Crawford",
              "Sam Rice",
              "Sam Thompson",
              "Sandy Koufax",
              "Satchel Paige",
              "Scott Rolen",
              "Stan Coveleski",
              "Stan Musial",
              "Steve Carlton",
              "Ted Lyons",
              "Ted Simmons",
              "Ted Williams",
              "Tim Keefe",
              "Tim Raines",
              "Todd Helton",
              "Tom Glavine",
              "Tom Seaver",
              "Tommy McCarthy",
              "Tony Gwynn",
              "Tony Lazzeri",
              "Tony Oliva",
              "Tony Perez",
              "Travis Jackson",
              "Trevor Hoffman",
              "Tris Speaker",
              "Turkey Stearnes",
              "Ty Cobb",
              "Vic Willis",
              "Vladimir Guerrero",
              "Wade Boggs",
              "Waite Hoyt",
              "Walter Johnson",
              "Warren Spahn",
              "Whitey Ford",
              "Willard Brown",
              "Willie Keeler",
              "Willie Mays",
              "Willie McCovey",
              "Willie Stargell",
              "Willie Wells",
              "Yogi Berra",
              "Zack Wheat"
            ],
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "DropdownView",
            "description": "Select Player:",
            "description_tooltip": null,
            "disabled": false,
            "index": 57,
            "layout": "IPY_MODEL_cbaca67b840d46b597edf447ca71a735",
            "style": "IPY_MODEL_22fca536071740098f38eac6f416429f"
          }
        },
        "cbaca67b840d46b597edf447ca71a735": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "22fca536071740098f38eac6f416429f": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "5593fe8deb274e33a9494a50ba609881": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DropdownModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DropdownModel",
            "_options_labels": [
              "% of Ballots",
              "ASG",
              "Born/Died",
              "Final Season",
              "Inducted",
              "Inducted As",
              "Rookie Season",
              "Voted By",
              "Votes",
              "Yrs"
            ],
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "DropdownView",
            "description": "Select Info:",
            "description_tooltip": null,
            "disabled": false,
            "index": 0,
            "layout": "IPY_MODEL_90ca7c71a98e48c0aaf1bc0a8111ba10",
            "style": "IPY_MODEL_ae67f6f446fd4cf3bdabd49851e5713f"
          }
        },
        "90ca7c71a98e48c0aaf1bc0a8111ba10": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "ae67f6f446fd4cf3bdabd49851e5713f": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "02839090251b44b0ad8cdc136c7e354d": {
          "model_module": "@jupyter-widgets/output",
          "model_name": "OutputModel",
          "model_module_version": "1.0.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/output",
            "_model_module_version": "1.0.0",
            "_model_name": "OutputModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/output",
            "_view_module_version": "1.0.0",
            "_view_name": "OutputView",
            "layout": "IPY_MODEL_665da38657654f33b37eeb1b1a2c0a21",
            "msg_id": "",
            "outputs": [
              {
                "output_type": "stream",
                "name": "stdout",
                "text": [
                  "\n",
                  "Details for: David Ortiz\n",
                  "       Name % of Ballots\n",
                  "David Ortiz        0.779\n"
                ]
              }
            ]
          }
        },
        "665da38657654f33b37eeb1b1a2c0a21": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "3a46f66014744c20bf041520320f0195": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DropdownModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DropdownModel",
            "_options_labels": [
              "Batting Stats",
              "Pitching Stats",
              "Other Stats"
            ],
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "DropdownView",
            "description": "Leaderboard Type:",
            "description_tooltip": null,
            "disabled": false,
            "index": 0,
            "layout": "IPY_MODEL_8b8a0380d8d74933af938a5e07c6caf4",
            "style": "IPY_MODEL_e5f3b28f17404fe98cf59288289877cc"
          }
        },
        "8b8a0380d8d74933af938a5e07c6caf4": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": "400px"
          }
        },
        "e5f3b28f17404fe98cf59288289877cc": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "6056a867e94c4a6ea99ed2822cdeacd1": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DropdownModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DropdownModel",
            "_options_labels": [
              "2B",
              "3B",
              "AB",
              "BA",
              "BB",
              "CS",
              "G",
              "GDP",
              "H",
              "HR",
              "IBB",
              "OBP",
              "OPS",
              "PA",
              "R",
              "RBI",
              "SB",
              "SF",
              "SH",
              "SLG",
              "SO",
              "WAR/pos"
            ],
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "DropdownView",
            "description": "Select Statistic:",
            "description_tooltip": null,
            "disabled": false,
            "index": 0,
            "layout": "IPY_MODEL_7b76eeb0531746d19f073a085a9978e2",
            "style": "IPY_MODEL_5cca8f8547464539b27f39a5dd097d97"
          }
        },
        "7b76eeb0531746d19f073a085a9978e2": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": "400px"
          }
        },
        "5cca8f8547464539b27f39a5dd097d97": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "a91b88c1f3954ce59368476cdbd90e28": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "IntTextModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "IntTextModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "IntTextView",
            "continuous_update": false,
            "description": "Amount Shown:",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_e480b3a9d76248eb92ed7eca4a511a24",
            "step": 1,
            "style": "IPY_MODEL_772946549b824711a23edae03f483f79",
            "value": 10
          }
        },
        "e480b3a9d76248eb92ed7eca4a511a24": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": "400px"
          }
        },
        "772946549b824711a23edae03f483f79": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "790220805eb6451b96c584c9f0b7e02f": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DropdownModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DropdownModel",
            "_options_labels": [
              "Leaders",
              "Losers"
            ],
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "DropdownView",
            "description": "Show:",
            "description_tooltip": null,
            "disabled": false,
            "index": 0,
            "layout": "IPY_MODEL_6ab14d8601054e32a8a3e7f26aeb8fc8",
            "style": "IPY_MODEL_4f2337b3c4394affa893e3987e951367"
          }
        },
        "6ab14d8601054e32a8a3e7f26aeb8fc8": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": "400px"
          }
        },
        "4f2337b3c4394affa893e3987e951367": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "1c7f7e5a727b4316ad2d1cb464111a0e": {
          "model_module": "@jupyter-widgets/output",
          "model_name": "OutputModel",
          "model_module_version": "1.0.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/output",
            "_model_module_version": "1.0.0",
            "_model_name": "OutputModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/output",
            "_view_module_version": "1.0.0",
            "_view_name": "OutputView",
            "layout": "IPY_MODEL_68305a5aef8e4a3cbbd412b151f21bc1",
            "msg_id": "",
            "outputs": [
              {
                "output_type": "stream",
                "name": "stdout",
                "text": [
                  "Leaders in 2B (Players only):\n",
                  " Rank             Name  2B\n",
                  "    1     Tris Speaker 792\n",
                  "    2      Stan Musial 725\n",
                  "    3          Ty Cobb 724\n",
                  "    4     Craig Biggio 668\n",
                  "    5     George Brett 665\n",
                  "    6       Nap Lajoie 657\n",
                  "    7 Carl Yastrzemski 646\n",
                  "    8     Honus Wagner 643\n",
                  "    9    Adrian Beltre 636\n",
                  "   10      David Ortiz 632\n"
                ]
              }
            ]
          }
        },
        "68305a5aef8e4a3cbbd412b151f21bc1": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        }
      }
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/erikgmarchant-dev/Hall-of-Fame-Database/blob/main/HallOfFameBBall.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "d23c91d8"
      },
      "source": [
        "### Step 1: Upload your Excel file\n",
        "\n",
        "Please upload your Excel file to your Colab environment (e.g., by dragging and dropping it into the files pane on the left)"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "print(\"Welcome to the Hall of Fame statistic bank (MLB).\")\n",
        "print(\"Toggle between the menus below to see the statistics\")\n",
        "print(\"of your favorite MLB Hall of Fame players.\")\n",
        "\n",
        "import pandas as pd\n",
        "\n",
        "# --- IMPORTANT: Update the filename below to your uploaded Excel file's name ---\n",
        "excel_filename = '/content/hall_of_fame_with_pitching.xlsx' # e.g., 'baseball_hof.xlsx'\n",
        "\n",
        "import ipywidgets as widgets\n",
        "from IPython.display import display, clear_output\n",
        "import pandas as pd # Ensure pandas is imported for pd.notna\n",
        "\n",
        "df_hof = pd.read_excel(excel_filename)\n",
        "\n",
        "# Rename 'From' column to 'Rookie Season'\n",
        "if 'From' in df_hof.columns:\n",
        "    df_hof = df_hof.rename(columns={'From': 'Rookie Season'})\n",
        "\n",
        "# Rename 'To' column to 'Final Season'\n",
        "if 'To' in df_hof.columns:\n",
        "    df_hof = df_hof.rename(columns={'To': 'Final Season'})\n",
        "\n",
        "PLAYER_NAME_COLUMN = 'Name'\n",
        "\n",
        "# Ensure df_hof and PLAYER_NAME_COLUMN are defined (from previous cells)\n",
        "if 'df_hof' in locals() and 'PLAYER_NAME_COLUMN' in locals():\n",
        "    # Get all columns except the player name column for the second dropdown\n",
        "    all_columns = df_hof.columns.tolist()\n",
        "    # Exclude columns that are likely to be empty for all players or are control columns\n",
        "    # 'Votes' and '% of Ballots' can be null if not inducted via BBWAA\n",
        "    # 'ASG', 'WAR/pos', 'G', 'PA', etc. are typically for players only\n",
        "    # Assuming all other columns are potential 'info_columns'\n",
        "    initial_info_columns = [col for col in all_columns if col != PLAYER_NAME_COLUMN]\n",
        "    initial_info_columns.sort() # Sort for consistent order\n",
        "\n",
        "    # Define 'Other Stats' columns including the newly requested ones\n",
        "    other_columns = ['ASG', 'Born/Died', 'Rookie Season', 'Final Season', 'Inducted', 'Inducted As', 'Voted By', 'Votes', '% of Ballots', 'Yrs']\n",
        "    other_columns = [col for col in other_columns if col in df_hof.columns] # Ensure they exist\n",
        "    other_columns.sort()\n",
        "\n",
        "    # Separate batting and pitching columns, excluding all 'other_columns'\n",
        "    batting_columns = [col for col in initial_info_columns if not col.endswith('(Pitching)') and col not in other_columns]\n",
        "    pitching_columns = [col for col in initial_info_columns if col.endswith('(Pitching)')]\n",
        "\n",
        "\n",
        "    # Get unique values for 'Inducted As' for the new 'Hall of Famer Type' dropdown\n",
        "    inducted_as_options = df_hof['Inducted As'].unique().tolist()\n",
        "    inducted_as_options.sort() # Sort for better readability\n",
        "    inducted_as_options.insert(0, 'All') # Add an 'All' option to show all types\n",
        "\n",
        "    if not initial_info_columns:\n",
        "        print(\"No other information columns found besides the player name.\")\n",
        "    else:\n",
        "        # Create the 'Hall of Famer Type' dropdown\n",
        "        inducted_as_selector = widgets.Dropdown(\n",
        "            options=inducted_as_options,\n",
        "            value='All', # Default to 'All'\n",
        "            description='Hall of Famer Type:', # Renamed description\n",
        "            disabled=False,\n",
        "        )\n",
        "\n",
        "        # Initialize player_selector (options will be updated dynamically)\n",
        "        player_selector = widgets.Dropdown(\n",
        "            options=[], # Start empty, will be populated by update_player_options\n",
        "            description='Select Player:',\n",
        "            disabled=False,\n",
        "        )\n",
        "\n",
        "        # Create the Stats Type dropdown (Batting/Pitching/Other)\n",
        "        stats_type_selector = widgets.Dropdown(\n",
        "            options=['Batting Stats', 'Pitching Stats', 'Other Stats'],\n",
        "            value='Batting Stats', # Default to batting stats\n",
        "            description='Stats Type:',\n",
        "            disabled=True, # Initially disabled, enable only for 'Player'\n",
        "        )\n",
        "\n",
        "        # Create the information type dropdown\n",
        "        info_selector = widgets.Dropdown(\n",
        "            options=[], # Start empty, will be populated by update_info_options\n",
        "            description='Select Info:',\n",
        "            disabled=False,\n",
        "        )\n",
        "\n",
        "        # Output widget to display player info dynamically\n",
        "        # Ensure output_widget is always created when the cell runs\n",
        "        output_widget = widgets.Output()\n",
        "\n",
        "        # Main function to display player information based on current selections\n",
        "        def update_display(change=None):\n",
        "            with output_widget:\n",
        "                clear_output(wait=True) # Clear previous output\n",
        "\n",
        "                selected_player = player_selector.value\n",
        "                selected_inducted_as = inducted_as_selector.value\n",
        "                selected_info_column = info_selector.value\n",
        "\n",
        "                # Only proceed if a player and an info column are selected\n",
        "                if not selected_player or not selected_info_column:\n",
        "                    print(\"Please make selections from all dropdowns.\")\n",
        "                    return\n",
        "\n",
        "                print(f\"\\nDetails for: {selected_player}\")\n",
        "\n",
        "                # Start with the full DataFrame and apply filters for display\n",
        "                filtered_df_for_display = df_hof.copy()\n",
        "\n",
        "                # Apply 'Hall of Famer Type' filter to the data being displayed\n",
        "                if selected_inducted_as != 'All':\n",
        "                    filtered_df_for_display = filtered_df_for_display[filtered_df_for_display['Inducted As'] == selected_inducted_as]\n",
        "\n",
        "                # Filter for the selected player from the *already filtered* display DataFrame\n",
        "                player_data = filtered_df_for_display[filtered_df_for_display[PLAYER_NAME_COLUMN] == selected_player]\n",
        "\n",
        "                if not player_data.empty:\n",
        "                    # Display only the selected information column\n",
        "                    # Ensure the selected_info_column actually exists in player_data before displaying\n",
        "                    if selected_info_column in player_data.columns:\n",
        "                        # Check if the column is numeric and needs formatting\n",
        "                        if pd.api.types.is_numeric_dtype(df_hof[selected_info_column]):\n",
        "                            # Define the custom formatter\n",
        "                            def format_numeric_for_display(val):\n",
        "                                if pd.isna(val):\n",
        "                                    return ''\n",
        "                                # Check if it's effectively an integer (e.g., 5.0 should become 5)\n",
        "                                if abs(val - round(val)) < 1e-9: # Compare with a small epsilon for float comparison\n",
        "                                    return str(int(round(val)))\n",
        "                                return str(val)\n",
        "\n",
        "                            # Create a temporary DataFrame for display with formatting\n",
        "                            display_df = player_data[[PLAYER_NAME_COLUMN, selected_info_column]].copy()\n",
        "                            display_df[selected_info_column] = display_df[selected_info_column].apply(format_numeric_for_display)\n",
        "                            print(display_df.to_string(index=False))\n",
        "                        else:\n",
        "                            # Non-numeric column, print directly\n",
        "                            print(player_data[[PLAYER_NAME_COLUMN, selected_info_column]].to_string(index=False))\n",
        "                    else:\n",
        "                        print(f\"Selected info column '{selected_info_column}' not available for this player.\")\n",
        "                else:\n",
        "                    print(\"Player data not found for the selected criteria. Please make sure a player is selected.\")\n",
        "\n",
        "        # Function to update the options of the info_selector based on selected player\n",
        "        def update_info_options(selected_player_name):\n",
        "            # Handle cases where selected_player_name might be empty (e.g., if no players for a category)\n",
        "            if not selected_player_name:\n",
        "                info_selector.options = []\n",
        "                info_selector.value = None\n",
        "                update_display() # Call update_display explicitly if no options result\n",
        "                return\n",
        "\n",
        "            # Get the row for the selected player\n",
        "            # Use .head(1) in case of multiple matches, though unique names should prevent this\n",
        "            player_row_df = df_hof[df_hof[PLAYER_NAME_COLUMN] == selected_player_name]\n",
        "            if player_row_df.empty:\n",
        "                info_selector.options = []\n",
        "                info_selector.value = None\n",
        "                update_display() # Call update_display explicitly if no player data\n",
        "                return\n",
        "            player_row = player_row_df.iloc[0]\n",
        "\n",
        "            # Determine which set of columns to consider based on Hall of Famer Type and Stats Type\n",
        "            relevant_columns_for_filter = []\n",
        "            if inducted_as_selector.value == 'Player':\n",
        "                if stats_type_selector.value == 'Batting Stats':\n",
        "                    relevant_columns_for_filter = batting_columns\n",
        "                elif stats_type_selector.value == 'Pitching Stats':\n",
        "                    relevant_columns_for_filter = pitching_columns\n",
        "                elif stats_type_selector.value == 'Other Stats':\n",
        "                    relevant_columns_for_filter = other_columns\n",
        "            else:\n",
        "                # For non-Player types, 'Other Stats' are often relevant, or a subset of initial_info_columns\n",
        "                relevant_columns_for_filter = [col for col in initial_info_columns if col in other_columns] # Only show relevant 'other' type for non-players\n",
        "                if not relevant_columns_for_filter: # Fallback if no relevant other columns\n",
        "                     relevant_columns_for_filter = initial_info_columns # Fallback to all initial for non-players if no specific 'other' fit\n",
        "\n",
        "            # Filter to only include those with non-null values for the player and are in the relevant_columns_for_filter\n",
        "            available_info_columns = [col for col in relevant_columns_for_filter if pd.notna(player_row[col])]\n",
        "            available_info_columns.sort()\n",
        "\n",
        "            info_selector.options = available_info_columns\n",
        "            if available_info_columns:\n",
        "                # If current value is not in new options, reset to first available\n",
        "                if info_selector.value not in available_info_columns:\n",
        "                    info_selector.value = available_info_columns[0]\n",
        "                else: # Value already present, but still need to trigger display to refresh output\n",
        "                    update_display()\n",
        "            else:\n",
        "                info_selector.value = None # No info columns available\n",
        "                update_display() # Call update_display explicitly if no options.\n",
        "\n",
        "\n",
        "        # Define a named function for player_selector to update info_options\n",
        "        def _player_changed_update_info(change):\n",
        "            update_info_options(change['new'])\n",
        "\n",
        "        # Function to update the options of the player_selector based on 'Hall of Famer Type' selection\n",
        "        def update_player_options_and_trigger_display(change):\n",
        "            selected_inducted_as_type = change['new']\n",
        "\n",
        "            # Filter df_hof to get players for the dropdown options\n",
        "            if selected_inducted_as_type == 'All':\n",
        "                players_for_dropdown = df_hof\n",
        "            else:\n",
        "                players_for_dropdown = df_hof[df_hof['Inducted As'] == selected_inducted_as_type]\n",
        "\n",
        "            # NEW LOGIC: Filter by pitching stats if 'Player' and 'Pitching Stats' are selected\n",
        "            if selected_inducted_as_type == 'Player' and stats_type_selector.value == 'Pitching Stats':\n",
        "                # Identify players who have at least one non-null pitching stat\n",
        "                players_with_pitching_stats = players_for_dropdown[players_for_dropdown[pitching_columns].notna().any(axis=1)]\n",
        "                players_for_dropdown = players_with_pitching_stats\n",
        "            # Also update player options if 'Other Stats' is selected, though it doesn't filter players by stats\n",
        "            elif selected_inducted_as_type == 'Player' and stats_type_selector.value == 'Other Stats':\n",
        "                 # For 'Other Stats', we don't filter players by their actual stats presence, but just display all players for 'Player' type.\n",
        "                 pass # No additional filtering needed based on 'Other Stats' for player list\n",
        "\n",
        "\n",
        "            new_player_names = players_for_dropdown[PLAYER_NAME_COLUMN].unique().tolist()\n",
        "            new_player_names.sort()\n",
        "\n",
        "            # Update player_selector options\n",
        "            player_selector.options = new_player_names\n",
        "            if new_player_names:\n",
        "                # If the currently selected player is not in the new options, reset to the first option\n",
        "                if player_selector.value not in new_player_names:\n",
        "                    player_selector.value = new_player_names[0]\n",
        "            else:\n",
        "                player_selector.value = None # Set to empty if no players are found for the category\n",
        "\n",
        "            # --- Logic for stats_type_selector ---\n",
        "            if selected_inducted_as_type == 'Player':\n",
        "                stats_type_selector.disabled = False\n",
        "            else:\n",
        "                stats_type_selector.disabled = True\n",
        "                stats_type_selector.value = 'Batting Stats' # Reset to default if not 'Player'\n",
        "                info_selector.options = [] # Clear info options if not a Player\n",
        "                info_selector.value = None\n",
        "\n",
        "            # After updating player options and value, update info options for the new player\n",
        "            # This will internally consider the stats_type_selector if it's a Player\n",
        "            update_info_options(player_selector.value if player_selector.options else None)\n",
        "\n",
        "        # New named function for stats_type_selector observation\n",
        "        def _stats_type_changed(change):\n",
        "            if inducted_as_selector.value == 'Player':\n",
        "                # If the Hall of Famer type is Player, changing stats type can affect player options\n",
        "                # This will re-evaluate players_for_dropdown based on pitching stats (if pitching selected)\n",
        "                update_player_options_and_trigger_display({'new': inducted_as_selector.value})\n",
        "            else:\n",
        "                # Otherwise, just update info options based on current player (which will be filtered by 'All' or other types)\n",
        "                update_info_options(player_selector.value)\n",
        "\n",
        "\n",
        "        # Attach all observers here BEFORE the initial trigger\n",
        "        # 'Hall of Famer Type' dropdown changes update the player dropdown options\n",
        "        inducted_as_selector.observe(update_player_options_and_trigger_display, names='value')\n",
        "        # Player dropdown changes update the displayed information AND the info_selector options\n",
        "        player_selector.observe(_player_changed_update_info, names='value') # Use the named function here\n",
        "        # Info dropdown changes update the displayed information\n",
        "        info_selector.observe(update_display, names='value')\n",
        "        # New: Stats Type dropdown changes update the info_selector options and then display\n",
        "        stats_type_selector.observe(_stats_type_changed, names='value')\n",
        "\n",
        "\n",
        "        # Display all dropdowns and the output area in the desired order\n",
        "        display(inducted_as_selector, stats_type_selector, player_selector, info_selector, output_widget)\n",
        "\n",
        "        # Initial setup: update player selector options based on the default 'Hall of Famer Type' value\n",
        "        # This will also trigger update_info_options and update_display implicitly.\n",
        "        update_player_options_and_trigger_display({'new': inducted_as_selector.value})\n",
        "\n",
        "else:\n",
        "    print(\"Please run the previous cells to load data and define 'df_hof' and 'PLAYER_NAME_COLUMN'.\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 267,
          "referenced_widgets": [
            "0603b853fec2405a86222c670e09c35b",
            "c89ef2222f23468aa01d3c1c2f0804b9",
            "e079135cbc564482bafba4967ac6ce48",
            "e239de91dcea453f8f46e7c4c0133a3f",
            "d32211b0612842f394b1bb1544b9811d",
            "eaf4b9ced5134ecb95f8e1e12180282d",
            "6b2781401d6046a38ed7031f5ab0434a",
            "cbaca67b840d46b597edf447ca71a735",
            "22fca536071740098f38eac6f416429f",
            "5593fe8deb274e33a9494a50ba609881",
            "90ca7c71a98e48c0aaf1bc0a8111ba10",
            "ae67f6f446fd4cf3bdabd49851e5713f",
            "02839090251b44b0ad8cdc136c7e354d",
            "665da38657654f33b37eeb1b1a2c0a21"
          ]
        },
        "id": "jVQofuQNv_p-",
        "outputId": "8972e7b2-2fb2-4a9c-bb26-cdee9278ee57"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Welcome to the Hall of Fame statistic bank (MLB).\n",
            "Toggle between the menus below to see the statistics\n",
            "of your favorite MLB Hall of Fame players.\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Dropdown(description='Hall of Famer Type:', options=('All', 'Manager', 'Pioneer/Executive', 'Player', 'Umpire'…"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "0603b853fec2405a86222c670e09c35b"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Dropdown(description='Stats Type:', disabled=True, options=('Batting Stats', 'Pitching Stats', 'Other Stats'),…"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "e239de91dcea453f8f46e7c4c0133a3f"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Dropdown(description='Select Player:', options=(), value=None)"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "6b2781401d6046a38ed7031f5ab0434a"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Dropdown(description='Select Info:', options=(), value=None)"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "5593fe8deb274e33a9494a50ba609881"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Output()"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "02839090251b44b0ad8cdc136c7e354d"
            }
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "print(\"This is the Hall of Fame Leaderboard (As of June 2026).\")\n",
        "print(\"Toggle between 'Batting,' 'Pitching,' and 'Other' stats\")\n",
        "print(\"and then choose the statistic that you want to see the leaderboard for.\")\n",
        "print(\"If you would like to see the Hall of Famers that were the worst\")\n",
        "print(\"at each statistic, toggle the fourth menu to 'Losers.'\")\n",
        "\n",
        "import ipywidgets as widgets\n",
        "from IPython.display import display, clear_output\n",
        "import pandas as pd\n",
        "\n",
        "# Assuming df_hof, PLAYER_NAME_COLUMN, batting_columns, and pitching_columns\n",
        "# are available from the previous cell's execution.\n",
        "# If this cell is run independently, these variables would need to be re-initialized.\n",
        "\n",
        "# Identify all numeric columns in df_hof for leaderboard purposes\n",
        "all_numeric_columns = [col for col in df_hof.columns if pd.api.types.is_numeric_dtype(df_hof[col])]\n",
        "\n",
        "# Define columns that are numeric but not typically used for a leaderboard ranking\n",
        "# (These are specifically for excluding from BAT_AND_PITCH_LEADERBOARDS, not 'Other Stats')\n",
        "exclude_from_bat_and_pitch_leaderboards = [\n",
        "    'Inducted', # Metadata/year columns\n",
        "    # Add any other columns you don't want to appear in the leaderboard 'Select Statistic' dropdown for batting/pitching\n",
        "]\n",
        "\n",
        "# Filter batting and pitching columns to only include numeric ones suitable for leaderboards\n",
        "numeric_batting_stats_for_leaderboard = [\n",
        "    col for col in batting_columns\n",
        "    if col in all_numeric_columns and col not in exclude_from_bat_and_pitch_leaderboards\n",
        "]\n",
        "numeric_pitching_stats_for_leaderboard = [\n",
        "    col for col in pitching_columns\n",
        "    if col in all_numeric_columns and col not in exclude_from_bat_and_pitch_leaderboards\n",
        "]\n",
        "\n",
        "# Define 'Other Stats' columns specifically for the leaderboard\n",
        "other_stats_columns_raw = ['% of Ballots', 'ASG', 'Votes', 'Yrs']\n",
        "numeric_other_stats_for_leaderboard = [\n",
        "    col for col in other_stats_columns_raw\n",
        "    if col in all_numeric_columns # Ensure they exist and are numeric\n",
        "]\n",
        "\n",
        "# Sort them for consistent display in the dropdowns\n",
        "numeric_batting_stats_for_leaderboard.sort()\n",
        "numeric_pitching_stats_for_leaderboard.sort()\n",
        "numeric_other_stats_for_leaderboard.sort()\n",
        "\n",
        "# 1. Create the 'Stats Type' dropdown for leaderboards\n",
        "leaderboard_stats_type_selector = widgets.Dropdown(\n",
        "    options=['Batting Stats', 'Pitching Stats', 'Other Stats'], # Added 'Other Stats'\n",
        "    value='Batting Stats',\n",
        "    description='Leaderboard Type:',\n",
        "    disabled=False,\n",
        "    layout={'width': '400px'},\n",
        "    description_width='200px'\n",
        ")\n",
        "\n",
        "# 2. Create the 'Select Info' menu for leaderboards\n",
        "leaderboard_info_selector = widgets.Dropdown(\n",
        "    options=[], # Populated dynamically\n",
        "    description='Select Statistic:',\n",
        "    disabled=False,\n",
        "    layout={'width': '400px'},\n",
        "    description_width='200px'\n",
        ")\n",
        "\n",
        "# 3. Create an input for the number of leaderboard members\n",
        "leaderboard_count_input = widgets.IntText(\n",
        "    value=10,\n",
        "    description='Amount Shown:',\n",
        "    disabled=False,\n",
        "    layout={'width': '400px'},\n",
        "    description_width='200px'\n",
        ")\n",
        "\n",
        "# 4. Create a new dropdown for 'Leaders' or 'Losers'\n",
        "leaderboard_direction_selector = widgets.Dropdown(\n",
        "    options=['Leaders', 'Losers'],\n",
        "    value='Leaders', # Default to leaders\n",
        "    description='Show:',\n",
        "    disabled=False,\n",
        "    layout={'width': '400px'},\n",
        "    description_width='200px'\n",
        ")\n",
        "\n",
        "# 5. Create an output widget for displaying the leaderboard\n",
        "leaderboard_output = widgets.Output()\n",
        "\n",
        "# Function to update the options of the leaderboard_info_selector\n",
        "def update_leaderboard_info_options(change=None):\n",
        "    selected_stats_type = leaderboard_stats_type_selector.value\n",
        "    if selected_stats_type == 'Batting Stats':\n",
        "        leaderboard_info_selector.options = numeric_batting_stats_for_leaderboard\n",
        "    elif selected_stats_type == 'Pitching Stats':\n",
        "        leaderboard_info_selector.options = numeric_pitching_stats_for_leaderboard\n",
        "    elif selected_stats_type == 'Other Stats': # Handle 'Other Stats'\n",
        "        leaderboard_info_selector.options = numeric_other_stats_for_leaderboard\n",
        "\n",
        "    # After updating options, ensure a value is selected and trigger display\n",
        "    # This also handles the case where there are no options for the selected type\n",
        "    if leaderboard_info_selector.options:\n",
        "        if leaderboard_info_selector.value not in leaderboard_info_selector.options:\n",
        "            leaderboard_info_selector.value = leaderboard_info_selector.options[0]\n",
        "    else:\n",
        "        leaderboard_info_selector.value = None\n",
        "\n",
        "    display_leaderboard() # Trigger leaderboard display regardless\n",
        "\n",
        "# Define the custom formatter for numeric values\n",
        "def format_numeric_for_display(val):\n",
        "    if pd.isna(val):\n",
        "        return ''\n",
        "    # Check if it's effectively an integer (e.g., 5.0 should become 5)\n",
        "    if abs(val - round(val)) < 1e-9: # Compare with a small epsilon for float comparison\n",
        "        return str(int(round(val)))\n",
        "    return str(val)\n",
        "\n",
        "# Function to display the top N leaderboard\n",
        "def display_leaderboard(change=None):\n",
        "    with leaderboard_output:\n",
        "        clear_output(wait=True)\n",
        "        selected_statistic = leaderboard_info_selector.value\n",
        "        top_n = leaderboard_count_input.value\n",
        "        display_direction = leaderboard_direction_selector.value # Get 'Leaders' or 'Losers'\n",
        "\n",
        "        if not selected_statistic:\n",
        "            print(\"Please select a statistic to view the leaderboard.\")\n",
        "            return\n",
        "        if top_n <= 0:\n",
        "            print(\"Please enter a positive number for 'Amount Shown'.\")\n",
        "            return\n",
        "\n",
        "        # Filter df_hof for 'Player' type Hall of Famers and non-null values for the selected statistic\n",
        "        leaderboard_df = df_hof[\n",
        "            (df_hof['Inducted As'] == 'Player') &\n",
        "            (df_hof[selected_statistic].notna())\n",
        "        ].copy() # Use .copy() to avoid SettingWithCopyWarning\n",
        "\n",
        "        if leaderboard_df.empty:\n",
        "            print(f\"No 'Player' type Hall of Famers with data for '{selected_statistic}' to form a leaderboard.\")\n",
        "            return\n",
        "\n",
        "        # Determine sorting order based on display_direction and statistic type\n",
        "        ascending_sort = False # Default for 'Leaders' (higher is better, so sort descending)\n",
        "\n",
        "        if selected_statistic in ['ERA (Pitching)', 'L  (Pitching)']: # Lower ERA and fewer Losses are better\n",
        "            # For these, 'Leaders' means ascending (lowest first), 'Losers' means descending (highest first)\n",
        "            ascending_sort = (display_direction == 'Leaders')\n",
        "        else:\n",
        "            # For all other stats, 'Leaders' means descending (highest first), 'Losers' means ascending (lowest first)\n",
        "            ascending_sort = (display_direction == 'Losers')\n",
        "\n",
        "        leaderboard_df_sorted = leaderboard_df.sort_values(\n",
        "            by=selected_statistic, ascending=ascending_sort\n",
        "        ).head(top_n).reset_index(drop=True)\n",
        "\n",
        "        # Add a 'Rank' column\n",
        "        leaderboard_df_sorted.insert(0, 'Rank', range(1, 1 + len(leaderboard_df_sorted)))\n",
        "\n",
        "        # Apply the custom formatting to the selected_statistic column if it's numeric\n",
        "        if pd.api.types.is_numeric_dtype(leaderboard_df_sorted[selected_statistic]):\n",
        "            leaderboard_df_sorted[selected_statistic] = leaderboard_df_sorted[selected_statistic].apply(format_numeric_for_display)\n",
        "\n",
        "        print(f\"{display_direction} in {selected_statistic} (Players only):\")\n",
        "        print(leaderboard_df_sorted[['Rank', PLAYER_NAME_COLUMN, selected_statistic]].to_string(index=False))\n",
        "\n",
        "\n",
        "# Attach observers\n",
        "leaderboard_stats_type_selector.observe(update_leaderboard_info_options, names='value')\n",
        "leaderboard_info_selector.observe(display_leaderboard, names='value')\n",
        "leaderboard_count_input.observe(display_leaderboard, names='value') # Observe changes in the new input\n",
        "leaderboard_direction_selector.observe(display_leaderboard, names='value') # Observe changes in the new direction input\n",
        "\n",
        "# Initial setup: Populate initial info options and display the first leaderboard\n",
        "update_leaderboard_info_options()\n",
        "\n",
        "# Display the widgets\n",
        "display(leaderboard_stats_type_selector, leaderboard_info_selector, leaderboard_count_input, leaderboard_direction_selector, leaderboard_output)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 450,
          "referenced_widgets": [
            "3a46f66014744c20bf041520320f0195",
            "8b8a0380d8d74933af938a5e07c6caf4",
            "e5f3b28f17404fe98cf59288289877cc",
            "6056a867e94c4a6ea99ed2822cdeacd1",
            "7b76eeb0531746d19f073a085a9978e2",
            "5cca8f8547464539b27f39a5dd097d97",
            "a91b88c1f3954ce59368476cdbd90e28",
            "e480b3a9d76248eb92ed7eca4a511a24",
            "772946549b824711a23edae03f483f79",
            "790220805eb6451b96c584c9f0b7e02f",
            "6ab14d8601054e32a8a3e7f26aeb8fc8",
            "4f2337b3c4394affa893e3987e951367",
            "1c7f7e5a727b4316ad2d1cb464111a0e",
            "68305a5aef8e4a3cbbd412b151f21bc1"
          ]
        },
        "id": "U1k_l5liPOyO",
        "outputId": "2c85ee64-73a8-4f35-e318-e2fd22d0ed58"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "This is the Hall of Fame Leaderboard (As of June 2026).\n",
            "Toggle between 'Batting,' 'Pitching,' and 'Other' stats\n",
            "and then choose the statistic that you want to see the leaderboard for.\n",
            "If you would like to see the Hall of Famers that were the worst\n",
            "at each statistic, toggle the fourth menu to 'Losers.'\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Dropdown(description='Leaderboard Type:', layout=Layout(width='400px'), options=('Batting Stats', 'Pitching St…"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "3a46f66014744c20bf041520320f0195"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Dropdown(description='Select Statistic:', layout=Layout(width='400px'), options=('2B', '3B', 'AB', 'BA', 'BB',…"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "6056a867e94c4a6ea99ed2822cdeacd1"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "IntText(value=10, description='Amount Shown:', layout=Layout(width='400px'))"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "a91b88c1f3954ce59368476cdbd90e28"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Dropdown(description='Show:', layout=Layout(width='400px'), options=('Leaders', 'Losers'), value='Leaders')"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "790220805eb6451b96c584c9f0b7e02f"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Output()"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "1c7f7e5a727b4316ad2d1cb464111a0e"
            }
          },
          "metadata": {}
        }
      ]
    }
  ]
}